#!/bin/bash

echo "Cleaning SSH known_hosts..."
echo

IPS=$(terraform output -json | jq -r '.. | .value? // empty | if type=="array" then .[] else . end')

for ip in $IPS; do
    echo "Removing $ip from known_hosts"
    ssh-keygen -R "$ip" >/dev/null 2>&1
done

echo
echo "Destroying infrastructure..."
terraform destroy --auto-approve | grep -E "Destroy complete"

# To avoid SSH host key errors, this script will take the instance IPs from the output.txt file generated by the deploy script, and remove them from the known_hosts file.
# This became a much needed solution as repeated deployments and wipes were causing SSH host key errors due to the IP addresses being reused by AWS.
# For lab purposes I would simply nuke the known_hosts file, but this is a more elegant solution that preserves any other SSH host keys you may have in there.
