- name: Update and Upgrade
  hosts: role_bastion,role_nat,role_private
  become: true
  gather_facts: false

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: Install locales-all
      ansible.builtin.apt:
        name: locales-all
        state: present

    - name: Ensure en_US.UTF-8 locale exists
      ansible.builtin.locale_gen:
        name: en_US.UTF-8
        state: present       

# - name: Update and Upgrade
#   hosts: all
#   gather_facts: false

#   pre_tasks:
#     - name: Wait for SSH to become available
#       ansible.builtin.wait_for_connection:
#         timeout: 300
#         delay: 5
#         sleep: 5

#   tasks:
#     - name: Update apt cache and upgrade packages
#       ansible.builtin.apt:
#         update_cache: yes
#         upgrade: dist
#       become: true

#     - name: Install locales-all
#       ansible.builtin.apt:
#         name: locales-all
#         state: present
#       become: true        