- name: Update and Upgrade Instances
  hosts: role_bastion,role_nat,role_private
  become: true
  gather_facts: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install locales-all
      ansible.builtin.apt:
        name: locales-all
        state: present
        